/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 6000
    gain: 23.0
    save_path: "" # 空表示不保存
    
/video_player:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    path: "/home/zcf/csurm/csurm-RMUC2022/ood_red(1).mp4"
    frame_rate: 30
    start_frame: 0
    frame_id: "camera_optical_frame"
    keep_looping: true              #是否循环播放    